#!/bin/bash

#sudo docker run -d -p 80:80 -p 443:443 -v /home/robin/html:/usr/html -v "$PWD/conf/nginx.conf":/etc/nginx/nginx.conf --name nginx_inst01 nginx
sudo docker run -d --network host -v /home/robin/html:/usr/html \
  -v "/home/robin/projects/docker_images/nginx/conf/nginx.conf":/etc/nginx/nginx.conf \
  -v "/home/robin/projects/docker_images/nginx/conf/ssl":/etc/nginx/ssl \
  --name nginx_inst01 nginx
