#!/bin/bash

# create volume 'pgdata' to store database
# sudo docker volume create pgdata

sudo docker run -d --env-file=env.list -p 5432:5432 \
  -v pgdata:/var/lib/postgresql/data --name postgres_inst01 postgres10_6
